version: '3.8'

services:
  postgres:
    container_name: pg-db
    image: postgres:15
    restart: always
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
